### ISSUE TITLE
Sorry, more of a question...

### ISSUE THREAD

**Issue by krcarriere** [ecsalomon/trust-game#1]
In Qualtrics, where are you finding the images IDs? I uploaded them to my Image Library, but it's still unclear to me.

**Comment by krcarriere** [comment]
Well, while I don't understand that at least it's working. I am confused on one thing though. It doesn't seem clear to me your assignments.

Your code talks about association. What association?

It's also set up to be either greedy, fair, or generous. From a few test runs, I assume this is constant for Rounds/2 (and then switches when the controller position switches). Is the best way to understand which one this is is to take the percent given back say percent =  returned1 / (gave1*3) ) where stingy=1 if percent<... and >... etc? 

Edit: Ah, it was explained in your readme. Is there a way to know which order the blocks appeared if keeping the controller via block?

**Comment by not-the-fish** [comment]
Hi, Kevin! The easiest way I found to handle the images in Qualtrics was to upload them to Libraries > File Libraries. Once they are uploaded, if you click on a file and then on the filename (e.g., `arrow16.png`), you'll be taken to the URL for that file. Copy everything _after_ `https://login.qualtrics.com/ControlPanel/File.php?F=` and enter that into the image ids. It's tedious, but Qualtics filenames are difficult.

The game was developed for my dissertation. I hoped to train an association between the power assignment and the trustworthiness of the partners (spoiler: It didn't generalize beyond the task). Training is a between-subjects condition that either pairs high and low power (Controller assignment) with different partner behavior (Association condition) or gives the same partner behavior in both power conditions (No Association condition). If you want to turn this off, it would be possible to set a constant value for `trainingCondition`. Use `0` to make partner behavior constant no matter who is able to punish, and use `1` to make partner behavior vary (between "stingy," "generous," and "fair")  with punishment ability.

You can adjust both the blocking of partner controller assignments and the values returned by the "stingy," "generous," and "fair" partners. To turn off the blocking of controller assignment, set `blockTrials` to `false`, and to change how much the partners return, adjust the mins and maxes for the three partner types. When `trainingCondition` is `0`, the "fair" partner plays. When `trainingCondition` is `1`, the stingy partner plays when the participant can punish, the generous partner plays when the partner may punish, and the fair partner plays when no one may punish.

... Speaking of which, you can set it up so that there are punishment-free rounds by making `roundMax` > `controller1Max` + `controller2Max`.

If you can tell me more about what you're using it for or how you'd like it to work, I can help a bit more with setting it up.

Hah, just saw your edit. I'll leave all of that for anyone else who has similar questions! 

It should be possible to get the blocking order; I'm pretty sure I looked at it when I had my data. I'll check my code and get back to you!

**Comment by not-the-fish** [comment]
Oh, right! One of the variables saved to Qualtrics is `controller1` ... `controller30` (or whatever number of rounds you have, but if you have more, you need to add the variables to the survey). Those will tell you who could punish on each round.

**Comment by krcarriere** [comment]
Thanks Erika! It's a really great repo, and I'm interested to read more about your work on it! 

I guess when I look at this, my question is how does a participant respond to a stingy player when the power level changes. Like, you have them being stingy when I can punish them (so assumingly, I will). Then we they have the chance to punish me, they're now generous. Shouldn't they also be stingy there too (and even more so, really). 

But I guess this set up is also super interesting, because you can do probably some interesting analysis between those who have their understandings of the partner betrayed (I thought he was stingy/generous and now he's generous/stingy) and those who didn't (Oh, he's always fair).

**Comment by not-the-fish** [comment]
Thanks, Kevin! When I used it, participants were told that they were paired with a different player on every round (and the avatar for Player 2 changes each round). Whether they believed that is uncertain.
